export const ROUTE_NAMES = {
  CREATE_WALLET: 'Create Wallet',
  LOGIN: 'Login',
  CHAT: 'Chat',
  COMMUNICATIONS: 'Communications',
  CONTACTS: 'Contacts',
  CREDENTIALS: 'Credentials',
  RELATIONSHIPS: 'Relationships',
  DEVELOPER: 'Developer',
  DEVELOPERS: 'Developers',
  MEDIATOR: 'Mediator',
  WALLET: 'Wallet',
  MAIN_TABS: 'mainTabs',
  REQUEST_CREDENTIAL: 'RequestCredential',
  RELATIONSHIP_DETAILS: 'Relationship Details',
  SIDE_TREE: 'Sidetree',
  SETTINGS: 'Settings',
  SAVE: 'Save',
  VCS: 'VCs',
  CREDENTIAL_DETAILS: 'Credential Details',
};
