export const ROUTE_NAMES = {
  CREATE_WALLET: 'Create Wallet',
  LOGIN: 'Login',
  CHAT: 'Chat',
  COMMUNICATIONS: 'Communications',
  CONTACTS: 'Contacts',
  CREDENTIALS: 'Credentials',
  DEVELOPER: 'Developer',
  DEVELOPERS: 'Developers',
  DID_DOCUMENT: 'DID Document',
  MEDIATOR: 'Mediator',
  WALLET: 'Wallet',
  MAIN_TABS: 'mainTabs',
  RELATIONSHIPS: 'Relationships',
  REQUEST_CREDENTIAL: 'RequestCredential',
  RELATIONSHIP_DETAILS: 'Relationship Details',
  SHOW_QR_CODE: 'Show_QR_Code',
  SCAN_QR_CODE: 'Scan_QR_Code',
  SIDE_TREE: 'Sidetree',
  SETTINGS: 'Settings',
  SAVE: 'Save',
  TEST: 'Test',
  VCS: 'VCs',
  CREDENTIAL_DETAILS: 'Credential Details',
  IDENTIFIER_DETAILS: 'Identifier Details',
};
